### ISSUE TITLE
local model

### ISSUE THREAD

**Issue by huongyj** [Dicklesworthstone/llm_aided_ocr#20]
Why am I reporting the following error：
`KeyError: slice(-1000, None, None)`

**Comment by huongyj** [comment]
I'm using the model that is automatically downloaded in the code



> 2024-09-10 11:25:08,617 - ERROR - An error occurred in the main function: slice(-1000, None, None)
> 2024-09-10 11:25:08,618 - ERROR - Traceback (most recent call last):
>   File "F:\download\pyenv\llm_aided_ocr\llm_aided_ocr.py", line 660, in main
>     final_text = await process_document(list_of_extracted_text_strings, reformat_as_markdown, suppress_headers_and_page_numbers)
>      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "F:\download\pyenv\llm_aided_ocr\llm_aided_ocr.py", line 568, in process_document
>     processed_chunks = await process_chunks(chunks, reformat_as_markdown, suppress_headers_and_page_numbers)
>                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "F:\download\pyenv\llm_aided_ocr\llm_aided_ocr.py", line 515, in process_chunks
>     processed_chunk, context = await process_chunk(chunk, context, i, total_chunks, reformat_as_markdown, suppress_headers_and_page_numbers)
>                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "F:\download\pyenv\llm_aided_ocr\llm_aided_ocr.py", line 501, in process_chunk
>     new_context = processed_chunk[-1000:]  # Use the last 1000 characters as context for the next chunk
>                   ~~~~~~~~~~~~~~~^^^^^^^^
> KeyError: slice(-1000, None, None)

**Comment by niujiangpu** [comment]
Hi have you solved your problem? Cause I've encountered exactly the same error.

**Comment by Dicklesworthstone** [comment]
This is related to #21 and #24 - the return type inconsistency is causing issues when trying to slice the result. Keeping open as part of the type-handling bug cluster.

**Comment by Dicklesworthstone** [comment]
Fixed in commit f5bb024. The `KeyError: slice(-1000, None, None)` was caused by `processed_chunk` being a dict instead of a string - dicts don't support slice notation with integers.

This was the same root cause as #21: `generate_completion_from_local_llm()` was returning a dict instead of a string. The function now consistently returns `Optional[str]`, so `processed_chunk[-1000:]` works correctly.
